addons:
  chrome: stable

language: node_js

node_js:
  - '12'

cache: npm

install:
  - npm ci
  - npm run init

script:
  - npm run validate
  - npm run build
  - npm run bundle
  - npm run test-cov
  - npm run check-format

  # Adjust HTML base path of example for deployment to GH pages
  - sed -i -e 's~<base href="/" />~<base href="/jsonforms-react-spectrum-renderers/" />~g' packages/spectrum/dist/index.html

after_success:
  - 'npm run merge-report && cat coverage/lcov.info | ./node_modules/.bin/coveralls'

deploy:
  provider: pages
  local_dir: packages/spectrum/dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
